version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: training_postgres
    env_file:
      - .env
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: training_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

volumes:
  postgres_data:
